---
title: "Eyetrackinganalysis"
author: "Vasilija Dolamic"
date: "2025-11-21"
output: html_document
---

```{r}
install.packages("https://cran.r-project.org/src/contrib/Archive/PupilPre/PupilPre_0.6.2.tar.gz", repos = NULL) #pupilpre no longer active on CRAN, need to install from archive
install.packages("eyelinker")
install.packages("dplyr")
install.packages("plyr")
install.packages("VWPre")
install.packages("shiny")
install.packages('robustbase')
install.packages("signal")
```

```{r}
require(PupilPre)
require(eyelinker)
require(plyr)
require(dplyr)
require(stringr)
require(ggplot2)
```
```{r}
rm(list=ls())
```

```{r}
source("eyetracking_in_R/src/asc_to_pupilpre.R")
```

```{r}
path_to_file <- "sub_1.asc"
raw_dat <- read.asc(path_to_file)
head(raw_dat)

```

```{r}
head(raw_dat$msg, 15)
```

```{r}
raw_dat$fix
```

```{r}
str(raw_dat)
head(raw_dat$msg$text,20)
tail(raw_dat$text$text,20)
```
```{r}
label <- "sub1" # Some subject identifier
recorded_eye <- "Left"
trial_start_msg <- "start trial [0-9]+" # Trial begin pattern
id_pattern <- "start trial " # Part of trial pattern used for trial index
trial_end_msg <- "end trial" # Trial end pattern
```

```{r}
ppl_pre_dat <- asc_to_pupilpre(path_to_file2,
                               label,
                               recorded_eye,
                               trial_start_msg,
                               id_pattern,
                               trial_end_msg)

```

```{r}
tail(ppl_pre_dat$pplpreData,100)
unique(ppl_pre_dat$pplpreData$TRIAL_INDEX)
#BRUH???
```
```{r}
head(ppl_pre_dat$rawMessages,20)
```
```{r}
head(ppl_pre_dat$rawData)
```


```{r}
dat <- ppl_pre_dat$pplpreData[ppl_pre_dat$pplpreData$in_trial,]
```

```{r}
str(dat)
```
```{r}
options(tibble.width = Inf)
```

```{r}
dat_aligned <- align_msg(dat,Msg="start trial")
str(dat_aligned)
```

```{r}
dat_time <- create_time_series(dat_aligned, Adjust = 0)
```

Check whether the results make sense for our messages:
```{r}
check_msg_time(dat_time, Msg = "start trial", ReturnData=T)
```

```{r}
check_msg_time(dat_time, Msg = "press spacebar", ReturnData = T)
```

```{r}
check_msg_time(dat_time, Msg = "rv_trial ",ReturnData = T)
```
```{r}
dat2 <- ppl_select_recorded_eye(data = dat_time, Recording = "LorR", WhenLandR = "Left")

```

```{r}
with(dat2,plot(Gaze_X,Gaze_Y))
```
```{r}
dat3 <- recode_off_screen(data = dat2, ScreenSize = c(1280, 1024))
```

```{r}
blink_summary(dat3, Summary = "Event")
```

```{r}
NA_summary(dat3, Summary = "Event", PupilColumn="Pupil")
```

```{r}

dat4 <- clean_blink(dat3, BlinkPadding = c(170, 170), Delta = 5,
                    MaxValueRun = 5, NAsAroundRun = c(2,2),
                    LogFile = "BlinkCleanupLog.rds")
```

```{r}

plot_compare_app(dat4)
```

```{r}
dat5 <- interpolate_NAs(dat4, Method = "linear", XandY = T, MinData = 2)
```

```{r}
plot_compare_app(dat5)
```

```{r}
dat6 <- baseline(dat5, BaselineWindow = c(-500, 0), BaselineType = "Subtraction")
```

```{r}
ppl_plot_avg(data = dat6, xlim = c(-250, 2000), Column = "Pupil",
             Condition1 = NULL, Condition2 = NULL, Cond1Labels = NA, 
             Cond2Labels = NA, ErrorBar = FALSE, ErrorBand=TRUE, PupilPreTheme = TRUE) 
```

```{r}
avg <- with(dat6[dat6$Time >= -250 & dat6$Time <= 2000,], aggregate(list(Pupil=Pupil), list(Time=Time),mean))
plot(avg$Time, avg$Pupil)
```


```{r}
easy_trials <- dat6 %>%
  filter(str_detect(SAMPLE_MESSAGE, "diff\\s+easy")) %>%
  pull(TRIAL_INDEX)

diff_trials <- dat6 %>%
  filter(str_detect(SAMPLE_MESSAGE, "diff\\s+difficult")) %>%
  pull(TRIAL_INDEX)

easy_trials
diff_trials

diff_index <-c(1,4,6,7,9,11,13,14,15,16,22,23,24,27,28,31,32,34,35,38,41,43,48,49,50,52,54,58,59,60,65,66,67,69,70,74,75,76,77,80,81,83,86,88,90,92,94,95,99,100,101,105,106,108,109,112,116,117,118,119)

dat6$diff <- ifelse(
  dat6$TRIAL_INDEX %in% diff_index,
  "diff",
  "easy")
head(dat6$diff)
tail(dat6$diff)
unique(dat6$diff)
tail(dat6$TRIAL_INDEX)
table(dat6$diff)
```

```{r}
dat6$diff <- as.factor(dat6$diff)
ppl_plot_avg(data = dat6, 
             xlim = c(-250, 2000), 
             Column = "Pupil",
             Condition1 = "diff",   # rlang unquote, or
             # Condition1 = eval(cond1),  # alternative
            , Condition2 = NULL,
             ErrorBar = FALSE, 
             ErrorBand = TRUE, 
             PupilPreTheme = TRUE) +
  scale_color_manual(values = c("easy" = "darkgreen", "diff" = "darkred"))

#figure out how to change colours
```

```{r}
dat_feedback <- dat6 %>% filter(TRIAL_INDEX %in% 1:60)
dat_nofeedback <- dat6 %>% filter(TRIAL_INDEX %in% 61:120)
with(dat_feedback,plot(Gaze_X,Gaze_Y,xlim=c(100,1400),ylim=c(0,1200)))
with(dat_nofeedback,plot(Gaze_X,Gaze_Y,xlim=c(100,1400),ylim=c(0,1200)))
#It is true if dynamic = 1 was with online feedback
```

```{r}
path_to_file2 <- "sub_2.asc"
raw_datsub2 <- read.asc(path_to_file2)
head(raw_datsub2)

path_to_file3 <- "sub_3.asc"
raw_datsub3 <- read.asc(path_to_file3)
head(raw_datsub3)
```
```{r}
ppl_pre_dat2 <- asc_to_pupilpre(path_to_file2,
                               label="sub2",
                               recorded_eye = "Left",
                               trial_start_msg ="start trial [0-9]+",
                               id_pattern ="start trial ",
                               trial_end_msg="end trial")

#MAIS


ppl_pre_dat3 <- asc_to_pupilpre(path_to_file3,
                               label="sub3",
                               recorded_eye = "Left",
                               trial_start_msg ="start trial [0-9]+",
                               id_pattern ="start trial ",
                               trial_end_msg="end trial")

```

```{r}
dats2 <- ppl_pre_dat2$pplpreData[ppl_pre_dat2$pplpreData$in_trial,]
dats3 <- ppl_pre_dat3$pplpreData[ppl_pre_dat3$pplpreData$in_trial,]
str(dats2)
str(dats3)
```

```{r}
dat2_aligned <- align_msg(dats2,Msg="start trial")
str(dat2_aligned)

dat3_aligned <- align_msg(dats3,Msg="start trial")
str(dat3_aligned)
```
```{r}
dat2_time <- create_time_series(dat2_aligned, Adjust = 0)
dat3_time <- create_time_series(dat3_aligned, Adjust = 0)


check_msg_time(dat2_time, Msg = "start trial", ReturnData=T)
check_msg_time(dat2_time, Msg = "press spacebar", ReturnData = T)

check_msg_time(dat3_time, Msg = "start trial", ReturnData=T)
check_msg_time(dat3_time, Msg = "press spacebar", ReturnData = T)
```

```{r}
dat2_s2 <- ppl_select_recorded_eye(data = dat2_time, Recording = "LorR", WhenLandR = "Left")
dat2_s3 <- ppl_select_recorded_eye(data = dat3_time, Recording = "LorR", WhenLandR = "Left")

```

```{r}
dat3_s2 <- recode_off_screen(data = dat2_s2, ScreenSize = c(1280, 1024))
blink_summary(dat3_s2, Summary = "Event")
NA_summary(dat3_s2, Summary = "Event", PupilColumn="Pupil")
dat4_s2 <- clean_blink(dat3_s2, BlinkPadding = c(170, 170), Delta = 5,
                    MaxValueRun = 5, NAsAroundRun = c(2,2),
                    LogFile = "BlinkCleanupLog.rds")
plot_compare_app(dat4_s2)
```
```{r}
dat3_s3 <- recode_off_screen(data = dat2_s3, ScreenSize = c(1280, 1024))
blink_summary(dat3_s3, Summary = "Event")
NA_summary(dat3_s3, Summary = "Event", PupilColumn="Pupil")
dat4_s3 <- clean_blink(dat3_s3, BlinkPadding = c(170, 170), Delta = 5,
                    MaxValueRun = 5, NAsAroundRun = c(2,2),
                    LogFile = "BlinkCleanupLog.rds")
plot_compare_app(dat4_s3)
#something seems off 
```
```{r}
dat5_s2 <- interpolate_NAs(dat4_s2, Method = "linear", XandY = T, MinData = 2)
plot_compare_app(dat5_s2)
```

```{r}
dat5_s3 <- interpolate_NAs(dat4_s3, Method = "linear", XandY = T, MinData = 2)
plot_compare_app(dat5_s3)
```
```{r}
dat6_s2 <- baseline(dat5_s2, BaselineWindow = c(-500, 0), BaselineType = "Subtraction")
dat6_s3 <- baseline(dat5_s3, BaselineWindow = c(-500, 0), BaselineType = "Subtraction")
```

```{r}
easy_trials <- dat6_s2 %>%
  filter(str_detect(SAMPLE_MESSAGE, "diff\\s+easy")) %>%
  pull(TRIAL_INDEX)

diff_trials <- dat6_s2 %>%
  filter(str_detect(SAMPLE_MESSAGE, "diff\\s+difficult")) %>%
  pull(TRIAL_INDEX)

easy_trials
diff_trials

easy_index <-c(3,4,5,9,10,13,15,17,18,19,22,23,24,25,28,31,32,33,38,39,42,45,47,49,50,52,53,55,56,59,61,63,65,66,70,71,73, 75,76,77,81,84,87,88,90,91,92,94,97,100,102,103,104,106,108,111,112,116,118,119)
length(easy_index)

dat6_s2$diff <- ifelse(
  dat6_s2$TRIAL_INDEX %in% easy_index,
  "easy",
  "diff")
head(dat6_s2$diff)

```

```{r}
easy_trials3 <- dat6_s3 %>%
  filter(str_detect(SAMPLE_MESSAGE, "diff\\s+easy")) %>%
  pull(TRIAL_INDEX)

diff_trials3 <- dat6_s3 %>%
  filter(str_detect(SAMPLE_MESSAGE, "diff\\s+difficult")) %>%
  pull(TRIAL_INDEX)

easy_trials3
diff_trials3

easy_index3 <-c(1,6,7,8,9,15,16,17,19,20,22,27,28,29,30,31,33,34,35,37,42,45,46,48,49,52,53,55,56,60,63,64,66,67,70,74,76,77,79,80,81,83,84,85,88,91,94,96,98,100,101,103,106,109,110,114,115,116,118,119)
length(easy_index3)

dat6_s3$diff <- ifelse(
  dat6_s3$TRIAL_INDEX %in% easy_index3,
  "easy",
  "diff")
head(dat6_s3$diff)

```

```{r}
dat6_s2$diff <- as.factor(dat6_s2$diff)
ppl_plot_avg(data = dat6_s2, 
             xlim = c(-250, 2000), 
             Column = "Pupil",
             Condition1 = "diff",   # rlang unquote, or
             # Condition1 = eval(cond1),  # alternative
            , Condition2 = NULL,
             ErrorBar = FALSE, 
             ErrorBand = TRUE, 
             PupilPreTheme = TRUE)

```

```{r}
dat6_s3$diff <- as.factor(dat6_s3$diff)
ppl_plot_avg(data = dat6_s3, 
             xlim = c(-250, 2000), 
             Column = "Pupil",
             Condition1 = "diff",   # rlang unquote, or
             # Condition1 = eval(cond1),  # alternative
            , Condition2 = NULL,
             ErrorBar = FALSE, 
             ErrorBand = TRUE, 
             PupilPreTheme = TRUE)
```
```{r}
dats2_nofeedback <- dat6_s2 %>% filter(TRIAL_INDEX %in% 1:60) 
dats2_feedback <- dat6_s2 %>% filter(TRIAL_INDEX %in% 61:120)
with(dats2_feedback,plot(Gaze_X,Gaze_Y,xlim=c(100,1400),ylim=c(0,1200)))
with(dats2_nofeedback,plot(Gaze_X,Gaze_Y,xlim=c(100,1400),ylim=c(0,1200)))
```
```{r}
dats3_feedback <- dat6_s3 %>% filter(TRIAL_INDEX %in% 1:60)
dats3_nofeedback <- dat6_s3 %>% filter(TRIAL_INDEX %in% 61:120)
with(dats3_feedback,plot(Gaze_X,Gaze_Y,xlim=c(100,1400),ylim=c(0,1200)))
with(dats3_nofeedback,plot(Gaze_X,Gaze_Y,xlim=c(100,1400),ylim=c(0,1200)))
```

# All subjects
```{r}
dat_all <- bind_rows(dat6, dat6_s2, dat6_s3)
head(dat_all)
```
```{r}
dat_all$diff <- as.factor(dat_all$diff)
ppl_plot_avg(data = dat_all, 
             xlim = c(-250, 2000), 
             Column = "Pupil",
             Condition1 = "diff",   # rlang unquote, or
             # Condition1 = eval(cond1),  # alternative
            , Condition2 = NULL,
             ErrorBar = FALSE, 
             ErrorBand = TRUE, 
             PupilPreTheme = TRUE)
```
```{r}
dat_all_feedback <- bind_rows(dat_feedback, dats2_feedback, dats3_feedback)
dat_all_nofeedback <- bind_rows(dat_nofeedback,dats2_nofeedback,dats3_nofeedback)
with(dat_all_feedback,plot(Gaze_X,Gaze_Y,xlim=c(100,1400),ylim=c(0,1200)))
with(dat_all_nofeedback,plot(Gaze_X,Gaze_Y,xlim=c(100,1400),ylim=c(0,1200)))
```

